type ClassSession = {
  id: number;
  subject: string;
  startTime: string;
  endTime: string;
  instructor: string;
  navigation: string;
  detailKey?: string;
};

type WeeklySchedule = {
  [key: string]: ClassSession[];
};

export const weeklyClasses: WeeklySchedule = {
  Holiday: [
    {
      id: 1,
      subject: "Treino Livre",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/livre",
    },
  ],
  Monday: [
    {
      id: 2,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 3,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 4,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 5,
      subject: "Treino Básico",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/iniciante",
      detailKey: "basicWhiteUpToThreeStripes",
    },
    {
      id: 6,
      subject: "Treino Infantil",
      startTime: "18:45",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 7,
      subject: "Treino Básico",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/iniciante",
      detailKey: "basicWhiteUpToThreeStripes",
    },
    {
      id: 8,
      subject: "Treino Avançado",
      startTime: "20:30",
      endTime: "21:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/avancado",
      detailKey: "advancedFromFourthStripeWhite",
    },
    {
      id: 9,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
      detailKey: "corujaoBasicIntermediate",
    },
  ],
  Tuesday: [
    {
      id: 10,
      subject: "Treino Feminino",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 11,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 12,
      subject: "Treino Avançado",
      startTime: "17:00",
      endTime: "18:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/avancado",
      detailKey: "advancedFromFourthStripeWhite",
    },
    {
      id: 13,
      subject: "Treino Baby",
      startTime: "18:00",
      endTime: "18:45",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 14,
      subject: "Treino Feminino",
      startTime: "18:45",
      endTime: "19:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 15,
      subject: "Treino Executivo (Acima de 35 anos)",
      startTime: "19:45",
      endTime: "20:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/executivo",
      detailKey: "executiveOver35",
    },
    {
      id: 16,
      subject: "Treino Básico/Intermediário",
      startTime: "20:45",
      endTime: "21:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 17,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
      detailKey: "corujaoBasicIntermediate",
    },
  ],
  Wednesday: [
    {
      id: 18,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 19,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 20,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 21,
      subject: "Treino Básico",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/iniciante",
      detailKey: "basicWhiteUpToThreeStripes",
    },
    {
      id: 22,
      subject: "Treino Infantil",
      startTime: "18:45",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 23,
      subject: "Treino Básico",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/iniciante",
      detailKey: "basicWhiteUpToThreeStripes",
    },
    {
      id: 24,
      subject: "Treino Avançado",
      startTime: "20:30",
      endTime: "21:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/avancado",
      detailKey: "advancedFromFourthStripeWhite",
    },
    {
      id: 25,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
      detailKey: "corujaoBasicIntermediate",
    },
  ],
  Thursday: [
    {
      id: 26,
      subject: "Treino Feminino",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 27,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 28,
      subject: "Treino Avançado",
      startTime: "17:00",
      endTime: "18:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/avancado",
      detailKey: "advancedFromFourthStripeWhite",
    },
    {
      id: 29,
      subject: "Treino Baby",
      startTime: "18:00",
      endTime: "18:45",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 30,
      subject: "Treino Feminino",
      startTime: "18:45",
      endTime: "19:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 31,
      subject: "Treino Executivo (Acima de 35 anos)",
      startTime: "19:45",
      endTime: "20:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/executivo",
      detailKey: "executiveOver35",
    },
    {
      id: 32,
      subject: "Treino (rola)",
      startTime: "20:45",
      endTime: "21:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/treino-rolas",
      detailKey: "sparringOnly",
    },
  ],
  Friday: [
    {
      id: 33,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 34,
      subject: "Treino Competição NO GI",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 35,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 36,
      subject: "Treino Básico/Intermediário",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 37,
      subject: "Treino Infantil",
      startTime: "18:45",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 38,
      subject: "Treino NO GI",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/nogi",
    },
  ],
  Saturday: [
    {
      id: 39,
      subject: "Tatame aberto",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/livre",
    },
  ],
};
