type ClassSession = {
  id: number;
  subject: string;
  startTime: string;
  endTime: string;
  instructor: string;
  navigation: string;
};

type WeeklySchedule = {
  [key: string]: ClassSession[];
};

export const weeklyClasses: WeeklySchedule = {
  Holiday: [
    {
      id: 1,
      subject: "Treino Livre",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/livre",
    },
  ],
  Monday: [
    {
      id: 2,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 3,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 34,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 4,
      subject: "Treino Básico/Intermediário",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 5,
      subject: "Treino Infantil",
      startTime: "18:30",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 6,
      subject: "Treino Básico/Intermediário",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 42,
      subject: "Treino Básico/Intermediário",
      startTime: "20:45",
      endTime: "21:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 43,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
    },
  ],
  Tuesday: [
    {
      id: 40,
      subject: "Treino Feminino",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 9,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 44,
      subject: "Treino Baby 1",
      startTime: "17:15",
      endTime: "18:00",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 45,
      subject: "Treino Baby 2",
      startTime: "18:00",
      endTime: "18:45",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 11,
      subject: "Treino Feminino",
      startTime: "18:45",
      endTime: "19:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 12,
      subject: "Treino Executivo (Acima de 35 anos)",
      startTime: "19:45",
      endTime: "20:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/executivo",
    },
    {
      id: 46,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
    },
  ],
  Wednesday: [
    {
      id: 15,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 16,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 35,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 17,
      subject: "Treino Básico/Intermediário",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 18,
      subject: "Treino Infantil",
      startTime: "18:30",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 19,
      subject: "Treino Básico/Intermediário",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 47,
      subject: "Treino Básico/Intermediário",
      startTime: "20:45",
      endTime: "21:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 48,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
    },
  ],
  Thursday: [
    {
      id: 41,
      subject: "Treino Feminino",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 23,
      subject: "Treino Competição",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 49,
      subject: "Treino Baby 1",
      startTime: "17:15",
      endTime: "18:00",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 50,
      subject: "Treino Baby 2",
      startTime: "18:00",
      endTime: "18:45",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 25,
      subject: "Treino Feminino",
      startTime: "18:45",
      endTime: "19:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/feminino",
    },
    {
      id: 26,
      subject: "Treino Executivo (Acima de 35 anos)",
      startTime: "19:45",
      endTime: "20:45",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/executivo",
    },
    {
      id: 51,
      subject: "Treino Corujão",
      startTime: "22:00",
      endTime: "23:00",
      instructor: "Matheus Pereira",
      navigation: "/academy/programs/corujao",
    },
  ],
  Friday: [
    {
      id: 28,
      subject: "Treino Básico",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Roni Júnior",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 29,
      subject: "Treino Competição NO GI",
      startTime: "12:00",
      endTime: "13:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/competicao",
    },
    {
      id: 36,
      subject: "Treino Básico",
      startTime: "15:30",
      endTime: "16:30",
      instructor: "Jeronimo Goulart",
      navigation: "/academy/programs/iniciante",
    },
    {
      id: 30,
      subject: "Treino Básico/Intermediário",
      startTime: "17:30",
      endTime: "18:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/intermediario",
    },
    {
      id: 31,
      subject: "Treino Infantil",
      startTime: "18:30",
      endTime: "19:30",
      instructor: "Monique Valadão",
      navigation: "/academy/programs/baby-kids-teen",
    },
    {
      id: 32,
      subject: "Treino NO GI",
      startTime: "19:30",
      endTime: "20:30",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/nogi",
    },
  ],
  Saturday: [
    {
      id: 33,
      subject: "Tatame aberto",
      startTime: "11:00",
      endTime: "12:00",
      instructor: "Fabiano Índio",
      navigation: "/academy/programs/livre",
    },
  ],
};
