type ClassSession = {
  id: number
  subject: string
  startTime: string
  endTime: string
  instructor: string
  navigation: string
}

type WeeklySchedule = {
  [key: string]: ClassSession[]
}

export const weeklyClasses: WeeklySchedule = {
  Holiday: [
    {
      id: 1,
      subject: 'Treino Livre',
      startTime: '11:00',
      endTime: '12:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/livre',
    },
  ],
  Monday: [
    {
      id: 2,
      subject: 'Treino Básico',
      startTime: '11:00',
      endTime: '12:00',
      instructor: 'Roni Júnior',
      navigation: '/academy/programs/iniciante',
    },
    {
      id: 3,
      subject: 'Treino Competição',
      startTime: '12:00',
      endTime: '13:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/competicao',
    },
    {
      id: 4,
      subject: 'Treino Básico/Intermediário',
      startTime: '17:30',
      endTime: '18:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 5,
      subject: 'Treino Kids',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Monique Valadão e Henrique Passos',
      navigation: '/academy/programs/baby-kids-teen',
    },
    {
      id: 6,
      subject: 'Treino Básico/Intermediário',
      startTime: '19:30',
      endTime: '20:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 7,
      subject: 'Treino Corujão',
      startTime: '22:00',
      endTime: '23:00',
      instructor: 'Matheus Pereira',
      navigation: '/academy/programs/corujao',
    },
  ],
  Tuesday: [
    {
      id: 8,
      subject: 'Treino Drills',
      startTime: '11:30',
      endTime: '12:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/avancado',
    },
    {
      id: 9,
      subject: 'Treino Competição',
      startTime: '12:00',
      endTime: '13:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/competicao',
    },
    {
      id: 10,
      subject: 'Treino Baby',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Monique Valadão',
      navigation: '/academy/programs/baby-kids-teen',
    },
    {
      id: 11,
      subject: 'Treino Feminino',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Felipe Zanini e Matheus Pereira',
      navigation: '/academy/programs/feminino',
    },
    {
      id: 12,
      subject: 'Treino Executivo',
      startTime: '19:30',
      endTime: '20:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/executivo',
    },
    {
      id: 13,
      subject: 'Treino Básico/Intermediário',
      startTime: '20:30',
      endTime: '21:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 14,
      subject: 'Treino Corujão',
      startTime: '22:00',
      endTime: '23:00',
      instructor: 'Matheus Pereira',
      navigation: '/academy/programs/corujao',
    },
  ],
  Wednesday: [
    {
      id: 15,
      subject: 'Treino Básico',
      startTime: '11:00',
      endTime: '12:00',
      instructor: 'Roni Júnior',
      navigation: '/academy/programs/iniciante',
    },
    {
      id: 16,
      subject: 'Treino Competição',
      startTime: '12:00',
      endTime: '13:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/competicao',
    },
    {
      id: 17,
      subject: 'Treino Básico/Intermediário',
      startTime: '17:30',
      endTime: '18:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 18,
      subject: 'Treino Kids',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Monique Valadão e Henrique Passos',
      navigation: '/academy/programs/baby-kids-teen',
    },
    {
      id: 19,
      subject: 'Treino Básico/Intermediário',
      startTime: '19:30',
      endTime: '20:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 20,
      subject: 'Treino NO GI',
      startTime: '20:30',
      endTime: '21:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/nogi',
    },
    {
      id: 21,
      subject: 'Treino Corujão',
      startTime: '22:00',
      endTime: '23:00',
      instructor: 'Matheus Pereira',
      navigation: '/academy/programs/corujao',
    },
  ],
  Thursday: [
    {
      id: 22,
      subject: 'Treino Drills',
      startTime: '11:30',
      endTime: '12:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/avancado',
    },
    {
      id: 23,
      subject: 'Treino Competição',
      startTime: '12:00',
      endTime: '13:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/competicao',
    },
    {
      id: 24,
      subject: 'Treino Baby',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Monique Valadão',
      navigation: '/academy/programs/baby-kids-teen',
    },
    {
      id: 25,
      subject: 'Treino Feminino',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Felipe Zanini e Matheus Pereira',
      navigation: '/academy/programs/feminino',
    },
    {
      id: 26,
      subject: 'Treino Executivo',
      startTime: '19:30',
      endTime: '20:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/executivo',
    },
    {
      id: 27,
      subject: 'Treino Básico/Intermediário',
      startTime: '20:30',
      endTime: '21:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
  ],
  Friday: [
    {
      id: 28,
      subject: 'Treino Básico',
      startTime: '11:00',
      endTime: '12:00',
      instructor: 'Roni Júnior',
      navigation: '/academy/programs/iniciante',
    },
    {
      id: 29,
      subject: 'Treino Competição',
      startTime: '12:00',
      endTime: '13:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/competicao',
    },
    {
      id: 30,
      subject: 'Treino Básico/Intermediário',
      startTime: '17:30',
      endTime: '18:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/intermediario',
    },
    {
      id: 31,
      subject: 'Treino Kids',
      startTime: '18:30',
      endTime: '19:30',
      instructor: 'Monique Valadão e Henrique Passos',
      navigation: '/academy/programs/baby-kids-teen',
    },
    {
      id: 32,
      subject: 'Treino NO GI',
      startTime: '19:30',
      endTime: '20:30',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/nogi',
    },
  ],
  Saturday: [
    {
      id: 33,
      subject: 'Treino Livre',
      startTime: '11:00',
      endTime: '12:00',
      instructor: 'Fabiano Índio',
      navigation: '/academy/programs/livre',
    },
  ],
}
